version: '3.8'

services:
  # Development server
  portfolio-dev:
    build: .
    ports:
      - "3000:80"
    volumes:
      - .:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    container_name: portfolio-dev
    restart: unless-stopped
    networks:
      - portfolio-network

  # Production server
  portfolio-prod:
    build: .
    ports:
      - "8080:80"
    container_name: portfolio-prod
    restart: unless-stopped
    networks:
      - portfolio-network
    profiles:
      - production

networks:
  portfolio-network:
    driver: bridge